/*
 * Exception.hpp
 *
 */
#ifndef INCLUDE_FILTER_PYTHON_EXCEPTION_HPP_FILE
#define INCLUDE_FILTER_PYTHON_EXCEPTION_HPP_FILE

#include "Filter/Exception.hpp"

namespace Filter
{
namespace Python
{
/** \brief base for all exceptions generated by python filter.
 */
class Exception: public Filter::Exception
{
public:
  /** \brief create execption with given message.
   *  \param where place where exception has been thrown.
   *  \param what  message to represent.
   */
  Exception(const Location &where, const std::string &what);
}; // class Exception

} // namespace Python
} // namespace Filter

#endif
