/*
 * Gloox.hpp
 *
 * helper wrapper that disables warnings generated by ICC when glib (indirectly
 * included by gloox) when it is included.
 */
#ifndef INCLUDE_TRIGGER_JABBER_GLOOX_HPP_FILE
#define INCLUDE_TRIGGER_JABBER_GLOOX_HPP_FILE

#ifdef __ICC
#pragma warning disable 1292
#endif

#include <gloox/client.h>
#include <gloox/message.h>
#include <gloox/messagehandler.h>
#include <gloox/messagesessionhandler.h>
#include <gloox/presence.h>

#ifdef __ICC
#pragma warning enable 1292
#endif

#endif
