#!/bin/bash

if [ "$#" -ne 1 ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]
then
  echo "$0 <wui_url>" >&2
  exit 3
fi

URL="$1/index.php?page=NagiosPlugin"
TMP="`mktemp`"
(
  # download list of heartbeats
  wget -q -O "$TMP" "$URL" > /dev/null || exit 3
  # senity check - when page could not be rendered (DB error, etc...)
  grep -v ' # ' "$TMP" > /dev/null && exit 3
  # return proper exit code
  CNT="`grep ' # DEAD$' "$TMP" | wc -l`"
  if [ "$CNT" -eq 0 ] || [ "$CNT" -eq 1 ]
  then
    exit "$CNT"
  else
    exit 2
  fi
)
# output data on the screen
RET="$?"
if [ "$RET" -eq 0 ]
then
  echo "RUNNING"
else
  echo "DEAD"
fi
cat "$TMP"
# clean up
rm -f "$TMP"
exit "$RET"
