#!/bin/bash
#
# ACARM-ng nagios plugin prepared as described in PL-Grid requirements:
# https://wiki.plgrid.pl/doku.php?id=pakiet3:dokumenty:monitorowanie
#

# helper outputing syntax and exiting
function print_help()
{
  echo "$0 <wui_url> [<timeout>]" >&2
  echo "$0 -H <wui_host> -t <timeout> [-s] [-p <port>] [-d <directory>]" >&2
  exit 3
}

# process command line paramters
case "$#" in
  #
  # first syntax
  #
  "1")
    URL="$1"
    TIME_OUT="30"
  ;;
  "2")
    URL="$1"
    TIME_OUT="$2"
  ;;

  #
  # second syntax
  #
  *)
    PROTO="http"
    while [ "$#" -gt 0 ]
    do
      case "$1" in
        "-h")
          print_help
        ;;
        "-H")
          ADDRESS="$2"
          shift
        ;;
        "-t")
          TIME_OUT="$2"
          shift
        ;;
        "-p")
          PORT="$2"
          shift
        ;;
        "-d")
          DIR="$2"
          shift
        ;;
        "-s")
          PROTO="https"
        ;;
        *)
          print_help
        ;;
      esac
      shift
    done

    [ ! -z "$PORT" ] && PORT=":$PORT"
    URL="$PROTO://$ADDRESS$PORT/$DIR/index.php?page=NagiosPlugin"

    # check if all required parametrs are given
    if [ -z "$ADDRESS" ] || [ -z "$TIME_OUT" ]
    then
      print_help
      # exit is called from the function
    fi
  ;;
esac


#
# processing it self
#
TMP="`mktemp`"
(
  # download list of heartbeats
  wget -T "$TIME_OUT" -q -O "$TMP" "$URL" > /dev/null || exit 3
  # senity check - when page could not be rendered (DB error, etc...)
  grep -v ' # ' "$TMP" > /dev/null && exit 3
  # return proper exit code
  CNT="`grep ' # DEAD$' "$TMP" | wc -l`"
  if [ "$CNT" -eq 0 ] || [ "$CNT" -eq 1 ]
  then
    exit "$CNT"
  else
    exit 2
  fi
)

#
# output data on the screen
#
RET="$?"
if [ "$RET" -eq 0 ]
then
  echo "RUNNING"
else
  echo "DEAD"
fi
cat "$TMP"

#
# clean up
#
rm -f "$TMP"
exit "$RET"
