#!/bin/bash

RET=0

# iterata through all build components
for d in `cat build_config/components{.,_test.}lst | sort | uniq | grep -v '^prelude$' | grep -v '^curlpp$'`
do
  echo "----------------------------"
  echo "testing $d:"
  ( cd gen/test_local_normal_default/$d && \
    LD_LIBRARY_PATH=../libs/ valgrind --leak-check=full --show-reachable=yes ./$d.t ) || RET=1
done

echo
if [ "$RET" -ne "0" ]
then
  echo "$0: some of the tests FAILED..."
fi

exit $RET
