#!/bin/bash

if [ "$#" -ne 1 ]
then
  echo "$0 <log_file>" >&2
  exit 1
fi

start=0
stop=0
sql="?"
export total=0
first=true

while read line
do
  t="`sed -e 's:^DEBUG@::' -e 's:/.*::' <<< "$line"`"
  if $first
  then
    sql="`sed 's#.*calling SQL statement: ##' <<< "$line"`"
    start="$t"
    first=false
  else
    stop="$t"
    diff="`bc -q <<< "$stop-$start"`"
    affected="`sed 's#.*: ##' <<< "$line"`"
    echo "[$diff]($affected) $sql"
    export total="$total+$diff"
    first=true
  fi
done < <(grep execSQL "$1")

echo "total time: `bc -q <<< "$total"`"
exit 0
