#!/bin/bash

# parameter requested
if test "$#" -ne "2"
then
  echo "$0 <file.log> <output/dir>" >&2
  exit 1
fi

LOG="$1"
shift
OUTDIR="$1"
shift

IDs="`pv "$LOG" | sed -e 's:^[^/]*/::' -e 's:^[^ ]* ::' -e 's:^\[::' -e 's:\].*::' | uniq | sort | uniq`"

# select separate ids into separete files
for id in $IDs
do
  echo "separating thread $id..."
  pv "$LOG" | grep " \[$id\] " > "$OUTDIR/thread_$id.log" || exit $?
done

exit 0
