#!/bin/bash

# parameter requested
if test "$#" -ne "2"
then
  echo "$0 <file.log> <output/dir>" >&2
  exit 1
fi

LOG="$1"
shift
OUTDIR="$1"
shift

IDs="`sed 's:^[^\[]*\[\([0-9]\+\)\].*:\1:' "$LOG" | sort | uniq`"

# select separate ids into separete files
for id in $IDs
do
  grep " \[$id\] " < "$LOG" > "$OUTDIR/thread_$id.log" || exit $?
done

exit 0
