#! /bin/sh
### BEGIN INIT INFO
# Provides:          acarm_ng
# Required-Start:    $network postgresql
# Required-Stop:     $network postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ACARM-ng startup script
# Description:       Runs/stops ACARM-ng system
#                    placed in /etc/init.d.
### END INIT INFO

# Author: Bartosz 'BaSz' Szurgot <bartosz.szurgot@pwr.wroc.pl>

# Do NOT "set -e"

# script setup
USER="acarm-ng"
GROUP="acarm-ng"
RUNLOG="$PREFIX/var/log/acarm-ng/run.log"
DAEMON="$PREFIX/bin/acarm-ng"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH="/sbin:/usr/sbin:/bin:/usr/bin"
DAEMON_ARGS="-d -u $USER -g $GROUP"
NAME="ACARM-ng"
APPNAME="acarm-ng.bin"

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

case "$1" in
  start)
    echo -n "starting $NAME (run log in $RUNLOG): "
    pidof "$APPNAME" > /dev/null 2>&1 && echo "deamon is already running" >&2 && exit 1
    mkdir -p "`dirname "$RUNLOG"`" || exit $?
    "$DAEMON" $DAEMON_ARGS >> "$RUNLOG" 2>&1
    RET="$?"
    if [ "$RET" -ne "0" ]
    then
      echo "FAILED"
    else
      echo "ok"
    fi
    exit "$RET"
  ;;

  stop)
    echo -n "stopping $NAME (may take some time): "
    # wait until process exits
    while pidof "$APPNAME" > /dev/null 2>&1
    do
      kill "`pidof "$APPNAME" 2>/dev/null`" > /dev/null 2>&1
      echo -n '.'
      sleep 1
    done
    echo
  ;;

  restart)
    "$0" stop
    "$0" start
  ;;

  *)
    echo "Usage: $0 {start|stop|restart}" >&2
    exit 3
  ;;
esac

exit 0
