#!/bin/bash

# parameter requested
if test "$#" -ne "2"
then
  echo "$0 <file.log> <output/dir>" >&2
  exit 1
fi

LOG="$1"
shift
OUTDIR="$1"
shift

echo "checking for threads' marks in log..."
IDs="`pv "$LOG" | cut -b20- | sed -e 's:^[^ ]* \[::' -e 's:\].*::' | uniq | sort -n | uniq`"
echo "threads found: `xargs echo -n <<< "$IDs"`"

# select separate ids into separete files
for id in $IDs
do
  echo "separating thread $id..."
  pv "$LOG" | grep " \[$id\] " > "$OUTDIR/thread_$id.log" || exit $?
done

exit 0
