#!/bin/bash
echo -n "checking for working g++... "
echo -e "#include <iostream>\nint main(void){return 0;}" > "$TMP"
if compile "$TMP"
then
  echo "ok"
else
  echo "N/A"
  echo "no working compiler found"
  rm -f "$TMP"
  exit 2
fi
