#!/bin/bash
# TODO: until there are more ICC licenses, we must stick to local builds witn Intel's compiler...
if grep -q "TC=intel" <<< "$@"
then
  #CPUS_LOCAL="`cat /proc/cpuinfo  | grep processor | wc -l`"
  exec make "-j1" "$@"
else
  CPUS_DIST="`distcc -j`"
  exec make WITH_DISTCC=1 "-j$CPUS_DIST" "$@"
fi
