#!/bin/bash

RET=0

# get component names from cmd-line, or run all if nothing given explicit
COMPONENTS="$*"
[ "$#" -eq 0 ] && COMPONENTS="`cat build_config/components{.,_test.}lst | sort | uniq | grep -v '^prelude$' | grep -v '^curlpp$'`"

# iterata through all build components
for d in $COMPONENTS
do
  echo "----------------------------"
  echo "testing $d:"
  SUPPS="`( for f in .misc/valgrind/*.supp ; do readlink -f "$f" | sed 's:^ *:--suppressions=:' ; done )`"
  if ! ( ulimit -c unlimited && \
         cd gen/test_gcc_normal_default/$d && \
         LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../libs/" valgrind --gen-suppressions=all --leak-check=full --show-reachable=yes $SUPPS ./$d.t 2>&1 | tee valgrind.log )
  then
    ((++RET))
    echo "$d group FAILED"
  fi
done

echo
if [ "$RET" -ne "0" ]
then
  echo "$0: some of the tests FAILED..."
fi

exit $RET
