#!/bin/bash

RET=0

MEM_MODE="normal"
[ "$#" -gt 0 ] && MEM_MODE="$1"

TC="local"
[ "$#" -gt 1 ] && TC="$2"

# iterata through all build components
for d in `cat build_config/components{.,_test.}lst | sort | uniq | grep -v '^prelude$' | grep -v '^curlpp$'`
do
  echo "----------------------------"
  echo "testing $d:"
  if ! ( ulimit -c unlimited && cd gen/test_${TC}_${MEM_MODE}_default/$d && LD_LIBRARY_PATH="$LD_LIBRARY_PATH:../libs/" ./$d.t )
  then
    RET=1
    echo "$d group FAILED"
  fi
done

echo
if [ "$RET" -ne "0" ]
then
  echo "$0: some of the tests FAILED..."
fi

exit $RET
